### PR TITLE
fix #13 introduced by commit 7a0aee9

### LINKED ISSUE #13: Strange uninstall mixture between itemtypes (same object id)
Hello,
I have a customer who, when he use the plugin to uninstall a Printer (ie ID 281), it's also uninstall the computer with the same ID! I've test with him and I can confirm the bug.

GLPI: 9.1
Uninstall 0.90-1.4

If necessary I can have a dump of his database.

Thank you

### PR DESCRIPTION
**Pull request by flegastelois**
Fix for #13

### CODE REVIEW

**Comment by trasher** [comment]
If this is a fix... There should be a htfix... Remember we're using gitflow now ;)

**Comment by flegastelois** [comment]
Okay,

hotfix/0.90-1.4.1 ?

**Comment by trasher** [comment]
1.4.1 or 1.4.0.1 ;)

**Comment by trasher** [comment]
Looks like I missed to add the version constant in this one... ould you please add it at the same time?

**Comment by wawax** [comment]
Merged here https://github.com/pluginsGLPI/uninstall/commit/a1870fc81adfc9177f7c5b01b278b79f67e74d2a

**Pull request closed without merging**
